---
# tasks file for .

- name: Install Docker's dependencies
  apt:
    name: "{{ item }}"
    update_cache: True
    cache_valid_time: "{{ docker_apt_cache_time }}"
  loop: "{{ docker_package_dependencies }}"

- name: Add Docker's GPG key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_server }}"

- name: Configure upstream APT repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"

- name: Install Docker
  apt:
    name: "docker"
    update_cache: true
    cache_valid_time: "{{ docker_apt_cache_time }}"
    state: "latest"

- name: Add user(s) to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: true
  loop: "{{ docker_users }}"
  when: not docker_remove_package and docker_users

